apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-mysql-from-vm2-only
  namespace: aichared-dev
spec:
  podSelector:
    matchLabels:
      app: mysql  # Cible ton Pod DB
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          kubevirt.io/domain: vm2-web # Autorise UNIQUEMENT la VM2
    ports:
    - protocol: TCP
      port: 3306
